export enum SagaStatus {
  STARTED = 'STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  COMPENSATING = 'COMPENSATING',
  COMPENSATED = 'COMPENSATED',
  COMPENSATED_WITH_ERRORS = 'COMPENSATED_WITH_ERRORS',
  FAILED = 'FAILED',
}
