"""
generate_estimate.py — PERT-based project estimate Excel generator
Part of the estimate-generator skill.

Usage:
    python generate_estimate.py --config estimate_config.json --output MyProject-Estimate.xlsx

Requires:
    pip install openpyxl

Config format (estimate_config.json):
{
  "project_name": "My Project",
  "sprint_length_days": 10,
  "hours_per_day": 8,
  "overhead_pct": 25,
  "contingency_pct": 15,
  "start_date": "YYYY-MM-DD",
  "team": {"FE": 1, "BE": 2, "QA": 1},
  "milestones": {"2": "M1 — Infrastructure Ready", "4": "M2 — Core Done"},
  "tasks": [
    {
      "phase": "Phase 0",
      "work_package": "Infrastructure",
      "task": "Terraform: VPC + Networking",
      "assignee": "BE1",
      "O": 8, "M": 16, "P": 24,
      "sprint": 1,
      "risk": "Medium",
      "notes": "ADR-0008"
    }
  ]
}
"""

import argparse
import json
import math
import sys
from datetime import date, timedelta

try:
    from openpyxl import Workbook
    from openpyxl.styles import (
        PatternFill, Font, Alignment, Border, Side, GradientFill
    )
    from openpyxl.utils import get_column_letter
except ImportError:
    print("ERROR: openpyxl not found. Install it with: pip install openpyxl")
    sys.exit(1)

# ── Colour palette ────────────────────────────────────────────────
DARK_BLUE   = "1F3864"
MID_BLUE    = "2E75B6"
LIGHT_BLUE  = "D5E8F0"
ALT_ROW     = "EAF3FB"
WHITE       = "FFFFFF"
NEAR_WHITE  = "F7F9FC"
HEADER_FG   = "FFFFFF"
DARK_TEXT   = "1A1A1A"
MILESTONE   = "FFF2CC"
RISK_HIGH   = "FFD7D7"
RISK_MED    = "FFF4DC"
RISK_LOW    = "D7F0D7"
RISK_CRIT   = "FFAAAA"
SUMMARY_BG  = "EEF4FF"
GREEN_TEXT  = "1F7A2E"
ORANGE_TEXT = "A05000"
RED_TEXT    = "A00000"

# ── Style helpers ─────────────────────────────────────────────────

def _fill(hex_color):
    return PatternFill(fill_type="solid", fgColor=hex_color)

def _font(bold=False, color=DARK_TEXT, size=10, italic=False):
    return Font(bold=bold, color=color, size=size, italic=italic, name="Calibri")

def _align(h="left", v="center", wrap=False):
    return Alignment(horizontal=h, vertical=v, wrap_text=wrap)

def _border(style="thin"):
    s = Side(style=style, color="CCCCCC")
    return Border(left=s, right=s, top=s, bottom=s)

def _thick_bottom():
    thick = Side(style="medium", color=MID_BLUE)
    thin  = Side(style="thin",   color="CCCCCC")
    return Border(left=thin, right=thin, top=thin, bottom=thick)

def style_header(cell, bg=MID_BLUE, fg=HEADER_FG, size=10, align="center"):
    cell.fill      = _fill(bg)
    cell.font      = _font(bold=True, color=fg, size=size)
    cell.alignment = _align(h=align, v="center")
    cell.border    = _border()

def style_cell(cell, bg=WHITE, bold=False, color=DARK_TEXT,
               align="left", wrap=False, italic=False):
    cell.fill      = _fill(bg)
    cell.font      = _font(bold=bold, color=color, italic=italic)
    cell.alignment = _align(h=align, v="center", wrap=wrap)
    cell.border    = _border()

def set_col_width(ws, col, width):
    ws.column_dimensions[get_column_letter(col)].width = width

# ── PERT calculation ─────────────────────────────────────────────

def pert(o, m, p):
    return round((o + 4 * m + p) / 6, 1)

def variance(o, p):
    return round(((p - o) / 6) ** 2, 2)

def risk_color(risk_level):
    r = risk_level.strip().lower()
    if r == "critical": return RISK_CRIT
    if r == "high":     return RISK_HIGH
    if r == "medium":   return RISK_MED
    return RISK_LOW

# ── Working-day calendar ─────────────────────────────────────────

def add_working_days(start: date, days: int) -> date:
    """Add `days` working days (Mon–Fri) to `start`."""
    current = start
    added = 0
    while added < days:
        current += timedelta(days=1)
        if current.weekday() < 5:   # 0=Mon … 4=Fri
            added += 1
    return current

def sprint_dates(start: date, sprint_num: int, sprint_days: int):
    """Return (sprint_start, sprint_end) for sprint_num (1-based)."""
    offset_days = (sprint_num - 1) * sprint_days
    sp_start = add_working_days(start, offset_days) if offset_days > 0 else start
    sp_end   = add_working_days(sp_start, sprint_days - 1)
    return sp_start, sp_end

# ── Sheet 1: Assumptions ─────────────────────────────────────────

def build_assumptions(wb, cfg):
    ws = wb.active
    ws.title = "Assumptions"
    ws.sheet_view.showGridLines = False

    # Title
    ws.merge_cells("A1:D1")
    c = ws["A1"]
    c.value = f"{cfg['project_name']} — Estimation Assumptions"
    c.fill      = _fill(DARK_BLUE)
    c.font      = _font(bold=True, color=WHITE, size=14)
    c.alignment = _align(h="left", v="center")
    ws.row_dimensions[1].height = 30

    # Subtitle
    ws.merge_cells("A2:D2")
    c = ws["A2"]
    c.value = "Generated by estimate-generator skill"
    c.fill      = _fill(MID_BLUE)
    c.font      = _font(color=WHITE, size=9, italic=True)
    c.alignment = _align(h="left", v="center")
    ws.row_dimensions[2].height = 16

    rows = [
        ("Project Parameters", None, None, True),
        ("Project Name",          cfg["project_name"],           "",    False),
        ("Sprint Length",         f"{cfg['sprint_length_days']} working days", "", False),
        ("Hours per Day",         f"{cfg['hours_per_day']} h",   "",    False),
        ("Overhead (Ceremonies)", f"{cfg['overhead_pct']}%",     "Standups, planning, retro, reviews", False),
        ("Contingency Buffer",    f"{cfg['contingency_pct']}%",  "Applied to raw PERT total", False),
        ("Project Start Date",    str(cfg.get("start_date", "TBD")), "", False),
        ("Team Composition", None, None, True),
    ]

    team = cfg.get("team", {})
    total_people = 0
    for role, count in team.items():
        rows.append((f"  {role} Developers", str(count), "", False))
        total_people += count
    rows.append(("  Total headcount", str(total_people), "", False))

    rows += [
        ("Capacity Model", None, None, True),
    ]

    gross = cfg["sprint_length_days"] * cfg["hours_per_day"]
    overhead_h = round(gross * cfg["overhead_pct"] / 100)
    effective  = gross - overhead_h
    usable     = round(effective * 0.90)
    team_cap   = usable * total_people

    rows += [
        ("Gross hours / person / sprint", f"{gross} h", "", False),
        ("Ceremony deduction",            f"{overhead_h} h", f"{cfg['overhead_pct']}% of gross", False),
        ("Effective hours / person / sprint", f"{effective} h", "", False),
        ("Usable hours / person / sprint",    f"{usable} h",    "90% of effective (10% sprint slack)", False),
        ("Total team capacity / sprint",      f"{team_cap} h",  f"{usable} h × {total_people} people", False),
    ]

    headers = ["Parameter", "Value", "Notes"]
    for col, h in enumerate(headers, start=1):
        c = ws.cell(row=3, column=col, value=h)
        style_header(c)
    ws.row_dimensions[3].height = 18

    row = 4
    for label, value, note, is_section in rows:
        if is_section:
            ws.merge_cells(f"A{row}:C{row}")
            c = ws.cell(row=row, column=1, value=label)
            c.fill      = _fill(LIGHT_BLUE)
            c.font      = _font(bold=True, color=DARK_BLUE, size=10)
            c.alignment = _align(h="left", v="center")
            c.border    = _border()
        else:
            bg = ALT_ROW if row % 2 == 0 else WHITE
            style_cell(ws.cell(row=row, column=1, value=label), bg=bg, bold=True)
            style_cell(ws.cell(row=row, column=2, value=value), bg=bg, align="center")
            style_cell(ws.cell(row=row, column=3, value=note),  bg=bg, italic=True,
                       color="666666")
        row += 1

    set_col_width(ws, 1, 38)
    set_col_width(ws, 2, 28)
    set_col_width(ws, 3, 50)

# ── Sheet 2: WBS + PERT ──────────────────────────────────────────

def build_wbs(wb, cfg):
    ws = wb.create_sheet("WBS + PERT")
    ws.sheet_view.showGridLines = False
    ws.freeze_panes = "A3"

    # Title row
    ws.merge_cells("A1:L1")
    c = ws["A1"]
    c.value = f"{cfg['project_name']} — Work Breakdown Structure + PERT Estimates"
    c.fill      = _fill(DARK_BLUE)
    c.font      = _font(bold=True, color=WHITE, size=13)
    c.alignment = _align(h="left", v="center")
    ws.row_dimensions[1].height = 28

    headers = ["Phase", "Work Package", "Task", "Assignee",
               "O (hrs)", "M (hrs)", "P (hrs)", "PERT (hrs)",
               "Variance", "Sprint", "Risk", "Notes"]
    for col, h in enumerate(headers, start=1):
        c = ws.cell(row=2, column=col, value=h)
        style_header(c)
    ws.row_dimensions[2].height = 18

    tasks = cfg.get("tasks", [])
    total_pert = 0.0
    total_var  = 0.0

    for i, t in enumerate(tasks):
        row = i + 3
        bg_risk = risk_color(t.get("risk", "Low"))
        bg_alt  = ALT_ROW if i % 2 == 0 else WHITE
        bg      = bg_risk  # colour rows by risk level for quick scanning

        o, m, p = t["O"], t["M"], t["P"]
        e = pert(o, m, p)
        v = variance(o, p)
        total_pert += e
        total_var  += v

        vals = [
            t.get("phase", ""),
            t.get("work_package", ""),
            t.get("task", ""),
            t.get("assignee", ""),
            o, m, p,
            e, round(v, 2),
            t.get("sprint", ""),
            t.get("risk", ""),
            t.get("notes", ""),
        ]
        aligns = ["left","left","left","center",
                  "center","center","center","center",
                  "center","center","center","left"]
        bolds  = [True, True, False, False,
                  False, False, False, True,
                  False, False, True, False]

        for col, (val, al, bo) in enumerate(zip(vals, aligns, bolds), start=1):
            c = ws.cell(row=row, column=col, value=val)
            style_cell(c, bg=bg, bold=bo, align=al,
                       wrap=(col == 3))  # wrap task description

    # Totals row — recompute locally for display (main() holds the canonical totals)
    local_pert = sum(pert(t["O"], t["M"], t["P"]) for t in tasks)
    local_var  = sum(variance(t["O"], t["P"]) for t in tasks)

    total_row = len(tasks) + 3
    ws.merge_cells(f"A{total_row}:G{total_row}")
    c = ws.cell(row=total_row, column=1, value="TOTAL (raw PERT)")
    c.fill      = _fill(MID_BLUE)
    c.font      = _font(bold=True, color=WHITE)
    c.alignment = _align(h="right")
    c.border    = _thick_bottom()

    c = ws.cell(row=total_row, column=8, value=round(local_pert, 1))
    c.fill      = _fill(MID_BLUE)
    c.font      = _font(bold=True, color=WHITE)
    c.alignment = _align(h="center")
    c.border    = _thick_bottom()

    c = ws.cell(row=total_row, column=9, value=round(local_var, 2))
    c.fill      = _fill(MID_BLUE)
    c.font      = _font(color=WHITE)
    c.alignment = _align(h="center")
    c.border    = _thick_bottom()

    # Column widths
    widths = [18, 22, 52, 12, 9, 9, 9, 11, 10, 9, 12, 30]
    for col, w in enumerate(widths, start=1):
        set_col_width(ws, col, w)

    ws.row_dimensions[1].height = 28
    for r in range(3, len(tasks) + 3):
        ws.row_dimensions[r].height = 20

# ── Sheet 3: Capacity Model ──────────────────────────────────────

def build_capacity(wb, cfg):
    ws = wb.create_sheet("Capacity Model")
    ws.sheet_view.showGridLines = False

    ws.merge_cells("A1:E1")
    c = ws["A1"]
    c.value = "Team Capacity Model"
    c.fill      = _fill(DARK_BLUE)
    c.font      = _font(bold=True, color=WHITE, size=13)
    c.alignment = _align(h="left", v="center")
    ws.row_dimensions[1].height = 28

    gross    = cfg["sprint_length_days"] * cfg["hours_per_day"]
    overhead = round(gross * cfg["overhead_pct"] / 100)
    eff      = gross - overhead
    usable   = round(eff * 0.90)

    headers = ["Role", "Headcount", "Gross h/sprint", "Ceremony h", "Effective h", "Usable h", "Team Capacity h"]
    for col, h in enumerate(headers, start=1):
        c = ws.cell(row=2, column=col, value=h)
        style_header(c)

    team = cfg.get("team", {})
    row = 3
    team_total = 0
    for role, count in team.items():
        bg = ALT_ROW if row % 2 == 0 else WHITE
        team_cap = usable * count
        team_total += team_cap
        vals = [role, count, gross * count, overhead * count,
                eff * count, usable * count, team_cap]
        bolds = [True, False, False, False, False, True, True]
        for col, (v, bo) in enumerate(zip(vals, bolds), start=1):
            style_cell(ws.cell(row=row, column=col, value=v),
                       bg=bg, bold=bo, align="center" if col > 1 else "left")
        row += 1

    # Team total row
    ws.merge_cells(f"A{row}:B{row}")
    c = ws.cell(row=row, column=1, value="TOTAL TEAM CAPACITY / SPRINT")
    c.fill = _fill(MID_BLUE); c.font = _font(bold=True, color=WHITE)
    c.alignment = _align(h="right"); c.border = _border()
    for col in range(3, 7):
        ws.cell(row=row, column=col).fill = _fill(MID_BLUE)
        ws.cell(row=row, column=col).border = _border()
    c = ws.cell(row=row, column=7, value=team_total)
    c.fill = _fill(MID_BLUE); c.font = _font(bold=True, color=WHITE)
    c.alignment = _align(h="center"); c.border = _border()

    # Notes
    row += 2
    notes = [
        ("Gross hours", f"sprint_days ({cfg['sprint_length_days']}) × hours_per_day ({cfg['hours_per_day']})"),
        ("Ceremony deduction", f"{cfg['overhead_pct']}% of gross (standups, planning, retro, reviews)"),
        ("Effective hours", "Gross − Ceremony"),
        ("Usable hours", "Effective × 90%  (10% sprint slack for unplanned work)"),
    ]
    for label, detail in notes:
        style_cell(ws.cell(row=row, column=1, value=label),
                   bg=NEAR_WHITE, bold=True)
        ws.merge_cells(f"B{row}:G{row}")
        style_cell(ws.cell(row=row, column=2, value=detail),
                   bg=NEAR_WHITE, italic=True, color="666666")
        row += 1

    widths = [30, 14, 16, 14, 14, 12, 20]
    for col, w in enumerate(widths, start=1):
        set_col_width(ws, col, w)

# ── Sheet 4: Sprint Plan ─────────────────────────────────────────

def build_sprint_plan(wb, cfg, tasks_with_pert):
    ws = wb.create_sheet("Sprint Plan")
    ws.sheet_view.showGridLines = False

    ws.merge_cells("A1:G1")
    c = ws["A1"]
    c.value = f"{cfg['project_name']} — Sprint Plan"
    c.fill      = _fill(DARK_BLUE)
    c.font      = _font(bold=True, color=WHITE, size=13)
    c.alignment = _align(h="left", v="center")
    ws.row_dimensions[1].height = 28

    milestones  = {int(k): v for k, v in cfg.get("milestones", {}).items()}
    start_date  = date.fromisoformat(cfg.get("start_date", str(date.today())))
    sprint_days = cfg["sprint_length_days"]
    gross       = sprint_days * cfg["hours_per_day"]
    overhead    = round(gross * cfg["overhead_pct"] / 100)
    usable      = round((gross - overhead) * 0.90)
    team        = cfg.get("team", {})
    total_people = sum(team.values())
    team_cap    = usable * total_people

    # Group tasks by sprint
    from collections import defaultdict
    sprints = defaultdict(list)
    for t in tasks_with_pert:
        sprints[int(t.get("sprint", 1))].append(t)

    row = 2
    for sprint_num in sorted(sprints.keys()):
        sp_start, sp_end = sprint_dates(start_date, sprint_num, sprint_days)
        sprint_tasks     = sprints[sprint_num]
        sprint_total     = sum(t["_pert"] for t in sprint_tasks)

        # Sprint header
        ws.merge_cells(f"A{row}:G{row}")
        label  = f"Sprint {sprint_num}  |  {sp_start.strftime('%d %b %Y')} – {sp_end.strftime('%d %b %Y')}"
        label += f"  |  PERT load: {round(sprint_total, 1)} h / {team_cap} h capacity"
        if sprint_num in milestones:
            label += f"  ★ {milestones[sprint_num]}"
        c = ws.cell(row=row, column=1, value=label)
        bg = MILESTONE if sprint_num in milestones else LIGHT_BLUE
        c.fill      = _fill(bg)
        c.font      = _font(bold=True, color=DARK_BLUE, size=10)
        c.alignment = _align(h="left")
        c.border    = _border()
        row += 1

        # Task header
        headers = ["Phase", "Work Package", "Task", "Assignee", "PERT (h)", "Risk", "Notes"]
        for col, h in enumerate(headers, start=1):
            c = ws.cell(row=row, column=col, value=h)
            style_header(c, bg="4472C4")
        row += 1

        for i, t in enumerate(sprint_tasks):
            bg_row = ALT_ROW if i % 2 == 0 else WHITE
            vals = [
                t.get("phase",""), t.get("work_package",""),
                t.get("task",""),  t.get("assignee",""),
                t["_pert"],        t.get("risk",""),
                t.get("notes",""),
            ]
            aligns = ["left","left","left","center","center","center","left"]
            bolds  = [False, False, False, True, True, False, False]
            for col, (val, al, bo) in enumerate(zip(vals, aligns, bolds), start=1):
                style_cell(ws.cell(row=row, column=col, value=val),
                           bg=bg_row, bold=bo, align=al,
                           wrap=(col == 3))
            row += 1

        # Spacer
        row += 1

    widths = [18, 22, 52, 12, 12, 12, 30]
    for col, w in enumerate(widths, start=1):
        set_col_width(ws, col, w)

# ── Sheet 5: Summary ─────────────────────────────────────────────

def build_summary(wb, cfg, total_pert, total_var):
    ws = wb.create_sheet("Summary")
    ws.sheet_view.showGridLines = False

    ws.merge_cells("A1:C1")
    c = ws["A1"]
    c.value = f"{cfg['project_name']} — Estimate Summary"
    c.fill      = _fill(DARK_BLUE)
    c.font      = _font(bold=True, color=WHITE, size=14)
    c.alignment = _align(h="left", v="center")
    ws.row_dimensions[1].height = 30

    contingency_pct = cfg["contingency_pct"] / 100
    contingency_h   = round(total_pert * contingency_pct, 1)
    total_with_buf  = round(total_pert + contingency_h, 1)
    total_sd        = round(math.sqrt(total_var), 1)
    p85_h           = round(total_pert + 1.0 * total_sd, 1)

    gross     = cfg["sprint_length_days"] * cfg["hours_per_day"]
    overhead  = round(gross * cfg["overhead_pct"] / 100)
    usable    = round((gross - overhead) * 0.90)
    team      = cfg.get("team", {})
    n_people  = sum(team.values())
    team_cap  = usable * n_people

    num_sprints = math.ceil(total_with_buf / team_cap)
    total_days  = num_sprints * cfg["sprint_length_days"]

    start_date  = date.fromisoformat(cfg.get("start_date", str(date.today())))
    go_live     = add_working_days(start_date, total_days)

    tasks       = cfg.get("tasks", [])
    n_tasks     = len(tasks)
    phases_set  = set(t.get("phase", "") for t in tasks)

    rows = [
        ("PROJECT OVERVIEW", None, True),
        ("Total tasks",                     str(n_tasks),                          ""),
        ("Total phases",                    str(len(phases_set)),                  ""),
        ("Team headcount",                  str(n_people),                         str(team)),
        ("PERT ESTIMATES", None, True),
        ("Raw PERT total",                  f"{total_pert:.1f} h",                 "Sum of all task PERT estimates"),
        ("Project std deviation (1σ)",      f"± {total_sd:.1f} h",                 "PERT variance across all tasks"),
        ("85% confidence estimate",         f"{p85_h:.1f} h",                      "Raw PERT + 1σ  (recommended for client commitment)"),
        ("CONTINGENCY & SCHEDULE", None, True),
        ("Contingency buffer",              f"{contingency_h:.1f} h ({cfg['contingency_pct']}%)", "Applied to raw PERT total"),
        ("Total estimate (with buffer)",    f"{total_with_buf:.1f} h",             "Raw PERT + contingency"),
        ("Team capacity / sprint",          f"{team_cap} h",                       f"{usable} h × {n_people} people"),
        ("Number of sprints",               str(num_sprints),                      f"ceil({total_with_buf:.1f} / {team_cap})"),
        ("Total calendar days",             str(total_days),                       f"{num_sprints} sprints × {cfg['sprint_length_days']} days"),
        ("DATES", None, True),
        ("Project start",                   str(start_date),                       ""),
        ("Projected go-live",               str(go_live),                          f"Start + {total_days} working days"),
        ("CONFIDENCE NOTE", None, True),
        ("Basis",                           "PERT three-point estimation",         "E = (O + 4M + P) / 6"),
        ("Contingency covers",              "Unidentified tasks, rework, minor scope changes", "Does NOT cover major scope changes"),
        ("For high-certainty commitment",   f"Use {p85_h:.1f} h (85% confidence)", "Or add further buffer at client discretion"),
    ]

    headers = ["Metric", "Value", "Notes"]
    for col, h in enumerate(headers, start=1):
        c = ws.cell(row=2, column=col, value=h)
        style_header(c)

    row = 3
    for item in rows:
        label, value, note = item
        is_section = (value is None)
        if is_section:
            ws.merge_cells(f"A{row}:C{row}")
            c = ws.cell(row=row, column=1, value=label)
            c.fill      = _fill(LIGHT_BLUE)
            c.font      = _font(bold=True, color=DARK_BLUE, size=10)
            c.alignment = _align(h="left", v="center")
            c.border    = _border()
        else:
            bg = SUMMARY_BG if row % 2 == 0 else WHITE
            # Highlight key rows
            if "go-live" in label.lower():
                bg = MILESTONE
            if "with buffer" in label.lower():
                bg = RISK_HIGH
            style_cell(ws.cell(row=row, column=1, value=label), bg=bg, bold=True)
            style_cell(ws.cell(row=row, column=2, value=value), bg=bg,
                       bold=("go-live" in label.lower() or "with buffer" in label.lower()),
                       align="center")
            style_cell(ws.cell(row=row, column=3, value=note),  bg=bg,
                       italic=True, color="666666")
        row += 1

    set_col_width(ws, 1, 42)
    set_col_width(ws, 2, 30)
    set_col_width(ws, 3, 55)

# ── Main ─────────────────────────────────────────────────────────

VALID_SHEETS = {"assumptions", "wbs", "capacity", "sprint", "summary"}

def parse_sheets(sheets_arg: str) -> set:
    """Parse --sheets argument into a set of sheet names."""
    if sheets_arg.strip().lower() == "all":
        return set(VALID_SHEETS)
    requested = {s.strip().lower() for s in sheets_arg.split(",")}
    unknown = requested - VALID_SHEETS
    if unknown:
        print(f"ERROR: Unknown sheet name(s): {unknown}")
        print(f"       Valid names: {', '.join(sorted(VALID_SHEETS))}  or  'all'")
        sys.exit(1)
    return requested


def main():
    parser = argparse.ArgumentParser(
        description="Generate PERT-based project estimate Excel",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Sheet options (--sheets):
  wbs           Task breakdown + PERT estimates (default, always the core output)
  assumptions   Project parameters and team composition
  capacity      Per-role gross/ceremony/effective/usable hours
  sprint        Tasks grouped by sprint with milestone markers
  summary       PERT totals, contingency, sprint count, go-live date
  all           All five sheets

Examples:
  --sheets wbs                     # WBS only (quick estimate)
  --sheets wbs,summary             # WBS + totals and go-live date
  --sheets wbs,sprint              # WBS + sprint-by-sprint breakdown
  --sheets all                     # Full project pack
        """
    )
    parser.add_argument("--config",  required=True,
                        help="Path to estimate_config.json")
    parser.add_argument("--output",  required=True,
                        help="Output .xlsx file path")
    parser.add_argument("--sheets",  default="wbs",
                        help="Comma-separated sheet names or 'all' (default: wbs)")
    args = parser.parse_args()

    # ── Parse sheet selection ────────────────────────────────────
    sheets = parse_sheets(args.sheets)

    # ── Load config ──────────────────────────────────────────────
    try:
        with open(args.config, encoding="utf-8") as f:
            cfg = json.load(f)
    except FileNotFoundError:
        print(f"ERROR: Config file not found: {args.config}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in config file: {e}")
        sys.exit(1)

    # ── Validate required fields ─────────────────────────────────
    required = ["project_name", "sprint_length_days", "hours_per_day",
                "overhead_pct", "contingency_pct", "team", "tasks"]
    missing = [f for f in required if f not in cfg]
    if missing:
        print(f"ERROR: Missing required config fields: {missing}")
        sys.exit(1)

    # ── Pre-compute PERT data (always — lightweight, needed for totals) ──
    tasks_with_pert = []
    total_pert = 0.0
    total_var  = 0.0
    for t in cfg["tasks"]:
        tc        = dict(t)
        tc["_pert"] = pert(t["O"], t["M"], t["P"])
        total_pert += tc["_pert"]
        total_var  += variance(t["O"], t["P"])
        tasks_with_pert.append(tc)

    # ── Build workbook — only requested sheets ───────────────────
    wb = Workbook()
    built = []

    if "assumptions" in sheets:
        print("Building Assumptions sheet...")
        build_assumptions(wb, cfg)
        built.append("Assumptions")

    if "wbs" in sheets:
        print("Building WBS + PERT sheet...")
        build_wbs(wb, cfg)
        built.append("WBS + PERT")

    if "capacity" in sheets:
        print("Building Capacity Model sheet...")
        build_capacity(wb, cfg)
        built.append("Capacity Model")

    if "sprint" in sheets:
        print("Building Sprint Plan sheet...")
        build_sprint_plan(wb, cfg, tasks_with_pert)
        built.append("Sprint Plan")

    if "summary" in sheets:
        print("Building Summary sheet...")
        build_summary(wb, cfg, total_pert, total_var)
        built.append("Summary")

    if not built:
        print("ERROR: No sheets were built. Check your --sheets argument.")
        sys.exit(1)

    # Remove the blank default sheet if it wasn't used as the first sheet
    if wb.worksheets[0].title == "Sheet" and len(wb.worksheets) > 1:
        del wb["Sheet"]

    # Set tab colours (cycle through palette)
    tab_colors = ["1F3864", "2E75B6", "4472C4", "538135", "70AD47"]
    for i, sheet in enumerate(wb.worksheets):
        sheet.sheet_properties.tabColor = tab_colors[i % len(tab_colors)]

    # ── Save ─────────────────────────────────────────────────────
    try:
        wb.save(args.output)
        contingency = round(total_pert * cfg["contingency_pct"] / 100, 1)
        print(f"\nDone!  Saved to: {args.output}")
        print(f"  Sheets generated : {', '.join(built)}")
        print(f"  Total tasks      : {len(cfg['tasks'])}")
        print(f"  Raw PERT total   : {total_pert:.1f} h")
        print(f"  With {cfg['contingency_pct']}% buffer  : {total_pert + contingency:.1f} h")
    except PermissionError:
        print(f"ERROR: Cannot write to {args.output} — close the file if it is open in Excel.")
        sys.exit(1)

if __name__ == "__main__":
    main()
